# Generated by Django 4.1.4 on 2022-12-25 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
                ('is_planted', models.BooleanField(default=False)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image_url', models.CharField(max_length=255)),
                ('date_added_to_list', models.DateTimeField(auto_now_add=True)),
                ('date_to_plant', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
